[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kurt-lang"
version = "0.1.0"
description = "The Kurt proof language and interpreter."
authors = [ { name = "Stefan Harmeling", email = "stefan.harmeling@tu-dortmund.de" } ]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = []    # runtime deps

[project.optional-dependencies]
dev = ["coverage"]

[project.scripts]
kurt = "kurt.kurt:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
kurt = ["theories/*.kurt"]
